# Generated by Django 5.2.17 on 2026-08-28 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='trackingeventlog',
            new_name='tracking_tr_event_n_71b2e5_idx',
            old_name='tracking_tr_event_n_2ac5cb_idx',
        ),
        migrations.RenameIndex(
            model_name='trackingeventlog',
            new_name='tracking_tr_status_e09729_idx',
            old_name='tracking_tr_status_998c61_idx',
        ),
    ]
