# Generated by Django 5.2.17 on 2026-08-22 03:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('order_number', models.CharField(db_index=True, max_length=40, unique=True)),
                ('customer_name', models.CharField(max_length=180)),
                ('customer_phone', models.CharField(db_index=True, max_length=24)),
                ('shipping_address_snapshot', models.JSONField(default=dict)),
                ('coupon_code_snapshot', models.CharField(blank=True, max_length=60)),
                ('promotion_snapshot', models.JSONField(blank=True, default=list)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('shipping_charge', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('order_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('packed', 'Packed'), ('ready_to_ship', 'Ready To Ship'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out For Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('return_requested', 'Return Requested'), ('returned', 'Returned'), ('partially_returned', 'Partially Returned'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=30)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('partial_refund', 'Partially Refunded'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=24)),
                ('fulfillment_status', models.CharField(choices=[('unfulfilled', 'Unfulfilled'), ('processing', 'Processing'), ('fulfilled', 'Fulfilled'), ('partial_return', 'Partially Returned'), ('returned', 'Returned')], db_index=True, default='unfulfilled', max_length=24)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_name_snapshot', models.CharField(max_length=220)),
                ('sku_snapshot', models.CharField(max_length=100)),
                ('variant_snapshot', models.JSONField(blank=True, default=dict)),
                ('image_snapshot', models.CharField(blank=True, max_length=500)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cost_price_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('returned_quantity', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
