# Generated by Django 5.2.17 on 2026-08-22 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='CheckoutSettings',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('created_at', models.DateTimeField(auto_now_add=True)),
        #         ('updated_at', models.DateTimeField(auto_now=True)),
        #         ('existing_customer_otp_verification', models.BooleanField(default=True, help_text='When enabled, anonymous checkout with an existing phone requires OTP before account access. When disabled, development can auto-login that existing customer after a successful order.', verbose_name='Existing customer OTP verification')),
        #     ],
        #     options={
        #         'verbose_name': 'Checkout setting',
        #         'verbose_name_plural': 'Checkout settings',
        #     },
        # ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('product_view', 'Product View'), ('add_to_cart', 'Add To Cart'), ('wishlist', 'Wishlist'), ('checkout_started', 'Checkout Started'), ('order_completed', 'Order Completed')], db_index=True, max_length=32)),
                ('session_token', models.CharField(blank=True, db_index=True, max_length=128)),
                ('cart_token', models.CharField(blank=True, db_index=True, max_length=128)),
                ('product_id_ref', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='common_anal_event_t_6bd2d8_idx'), models.Index(fields=['product_id_ref', 'created_at'], name='common_anal_product_65917a_idx')],
            },
        ),
    ]
