# Generated by Django 5.2.17 on 2026-08-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('existing_customer_otp_verification', models.BooleanField(default=True, help_text='When enabled, anonymous checkout with an existing phone requires OTP before account access. When disabled, development can auto-login that existing customer after a successful order.', verbose_name='Existing customer OTP verification')),
            ],
            options={
                'verbose_name': 'Checkout setting',
                'verbose_name_plural': 'Checkout settings',
            },
        ),
    ]
