# Generated by Django 5.2.17 on 2026-08-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_checkoutsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eyebrow', models.CharField(blank=True, max_length=120)),
                ('title', models.CharField(max_length=180)),
                ('subtitle', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='hero_slides/')),
                ('mobile_image', models.ImageField(blank=True, null=True, upload_to='hero_slides/mobile/')),
                ('image_alt', models.CharField(blank=True, max_length=180)),
                ('primary_cta_label', models.CharField(blank=True, max_length=80)),
                ('primary_cta_url', models.CharField(blank=True, max_length=255)),
                ('secondary_cta_label', models.CharField(blank=True, max_length=80)),
                ('secondary_cta_url', models.CharField(blank=True, max_length=255)),
                ('text_position', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=12)),
                ('theme', models.CharField(choices=[('light', 'Light text'), ('dark', 'Dark text')], default='dark', max_length=12)),
                ('overlay_opacity', models.PositiveSmallIntegerField(default=20, help_text='Background overlay opacity from 0 to 90 percent.')),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('starts_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'ordering': ('order', 'id'),
                'indexes': [models.Index(fields=['active', 'order'], name='common_hero_active_6847f9_idx')],
            },
        ),
    ]
