# Generated by Django 5.2.17 on 2026-08-26 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_heroslide'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=240)),
                ('icon', models.CharField(blank=True, help_text='Optional icon key: gift, truck, sparkles, badge, tag, shield.', max_length=32)),
                ('link_url', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'ordering': ('order', 'id'),
                'indexes': [models.Index(fields=['active', 'order'], name='common_anno_active_628816_idx')],
            },
        ),
    ]
