# Generated by Django 5.2.17 on 2026-08-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_announcementmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnnouncementMessage',
        ),
        migrations.AddField(
            model_name='checkoutsettings',
            name='google_tag_manager_id',
            field=models.CharField(blank=True, help_text='Example: GTM-ABC1234', max_length=32, verbose_name='Google Tag Manager container ID'),
        ),
        migrations.AddField(
            model_name='checkoutsettings',
            name='meta_pixel_id',
            field=models.CharField(blank=True, help_text='Exposed to Google Tag Manager through the dataLayer as meta_pixel_id.', max_length=64, verbose_name='Meta Pixel ID'),
        ),
        migrations.AddField(
            model_name='checkoutsettings',
            name='tracking_enabled',
            field=models.BooleanField(default=False, help_text='Loads Google Tag Manager on the public storefront when a valid GTM container ID is configured.', verbose_name='Storefront tracking enabled'),
        ),
    ]
