# Generated by Django 5.2.17 on 2026-08-28 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_delete_announcementmessage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutsettings',
            name='google_tag_manager_id',
        ),
        migrations.RemoveField(
            model_name='checkoutsettings',
            name='meta_pixel_id',
        ),
        migrations.RemoveField(
            model_name='checkoutsettings',
            name='tracking_enabled',
        ),
    ]
