# Generated by Django 5.2.17 on 2026-08-22 03:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=60, unique=True)),
                ('coupon_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount'), ('free_shipping', 'Free Shipping')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('minimum_spend', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('usage_limit_per_customer', models.PositiveIntegerField(blank=True, null=True)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('first_order_only', models.BooleanField(default=False)),
                ('brands', models.ManyToManyField(blank=True, related_name='coupons', to='catalog.brand')),
                ('categories', models.ManyToManyField(blank=True, related_name='coupons', to='catalog.category')),
                ('customers', models.ManyToManyField(blank=True, related_name='coupons', to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(blank=True, related_name='coupons', to='catalog.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='promotions.coupon')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usage', to='orders.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('promotion_type', models.CharField(choices=[('bogo', 'BOGO'), ('buy_x_get_y', 'Buy X Get Y'), ('brand_discount', 'Brand Discount'), ('category_discount', 'Category Discount'), ('product_discount', 'Product Discount'), ('flash_sale', 'Flash Sale'), ('order_value', 'Order Value'), ('first_order', 'First Order')], db_index=True, max_length=30)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('combinable', models.BooleanField(default=False)),
                ('config', models.JSONField(default=dict, help_text='Auditable rule configuration')),
                ('brands', models.ManyToManyField(blank=True, related_name='promotions', to='catalog.brand')),
                ('categories', models.ManyToManyField(blank=True, related_name='promotions', to='catalog.category')),
                ('products', models.ManyToManyField(blank=True, related_name='promotions', to='catalog.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
