# Generated by Django 5.2.17 on 2026-08-22 03:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('contact_person', models.CharField(blank=True, max_length=140)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('payment_terms', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_number', models.CharField(db_index=True, max_length=40, unique=True)),
                ('supplier_invoice', models.CharField(blank=True, max_length=100)),
                ('purchase_date', models.DateField()),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('partial', 'Partially Received'), ('received', 'Received'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases_created', to=settings.AUTH_USER_MODEL)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases_received', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='inventory.supplier')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='inventory.warehouse')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_item', to='catalog.product')),
                ('variant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_item', to='catalog.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField()),
                ('reference_type', models.CharField(db_index=True, max_length=60)),
                ('reference_id', models.CharField(db_index=True, max_length=80)),
                ('consumed', models.BooleanField(default=False)),
                ('released', models.BooleanField(default=False)),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='inventory.stockitem')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='inventory.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('return', 'Return'), ('cancellation', 'Cancellation'), ('adjustment', 'Adjustment'), ('damage', 'Damage'), ('transfer', 'Transfer'), ('restock', 'Restock'), ('reservation', 'Reservation'), ('release', 'Release')], db_index=True, max_length=20)),
                ('quantity', models.IntegerField()),
                ('before_quantity', models.PositiveIntegerField()),
                ('after_quantity', models.PositiveIntegerField()),
                ('reference_type', models.CharField(blank=True, db_index=True, max_length=60)),
                ('reference_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.stockitem')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('available_stock', models.PositiveIntegerField(default=0)),
                ('reserved_stock', models.PositiveIntegerField(default=0)),
                ('damaged_stock', models.PositiveIntegerField(default=0)),
                ('incoming_stock', models.PositiveIntegerField(default=0)),
                ('reorder_level', models.PositiveIntegerField(default=0)),
                ('low_stock_threshold', models.PositiveIntegerField(default=0)),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='inventory.stockitem')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='inventory.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField()),
                ('received_quantity', models.PositiveIntegerField(default=0)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='catalog.product')),
                ('product_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='catalog.productvariant')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.purchase')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('product__isnull', False), ('product_variant__isnull', True)), models.Q(('product__isnull', True), ('product_variant__isnull', False)), _connector='OR'), name='purchase_item_exactly_one_target'), models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='purchase_item_quantity_gt_zero'), models.CheckConstraint(condition=models.Q(('received_quantity__lte', models.F('quantity'))), name='purchase_received_lte_ordered')],
            },
        ),
        migrations.AddConstraint(
            model_name='stockitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('product__isnull', False), ('variant__isnull', True)), models.Q(('product__isnull', True), ('variant__isnull', False)), _connector='OR'), name='stock_item_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='stockreservation',
            constraint=models.UniqueConstraint(fields=('stock_item', 'warehouse', 'reference_type', 'reference_id'), name='unique_stock_reservation_ref'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['stock_item', 'created_at'], name='inventory_s_stock_i_c40196_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['reference_type', 'reference_id'], name='inventory_s_referen_5aaa1a_idx'),
        ),
        migrations.AddIndex(
            model_name='productstock',
            index=models.Index(fields=['warehouse', 'available_stock'], name='inventory_p_warehou_6dd755_idx'),
        ),
        migrations.AddIndex(
            model_name='productstock',
            index=models.Index(fields=['stock_item', 'available_stock'], name='inventory_p_stock_i_5d5b87_idx'),
        ),
        migrations.AddConstraint(
            model_name='productstock',
            constraint=models.UniqueConstraint(fields=('stock_item', 'warehouse'), name='unique_stock_item_warehouse'),
        ),
    ]
