# Generated by Django 5.2.17 on 2026-08-22 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(choices=[('inside_dhaka', 'Inside Dhaka'), ('outside_dhaka', 'Outside Dhaka'), ('subarea', 'Subarea')], max_length=40, unique=True)),
                ('charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('delivery_module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='delivery.deliverymodule')),
            ],
            options={
                'ordering': ('name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Thana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(db_index=True, max_length=160)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thanas', to='delivery.city')),
                ('delivery_module', models.ForeignKey(blank=True, help_text='Optional override. Leave empty to inherit the district delivery module.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='thanas', to='delivery.deliverymodule')),
            ],
            options={
                'ordering': ('name', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['active', 'name'], name='delivery_ci_active_bb0ae0_idx'),
        ),
        migrations.AddIndex(
            model_name='thana',
            index=models.Index(fields=['city', 'active', 'name'], name='delivery_th_city_id_307bfb_idx'),
        ),
        migrations.AddConstraint(
            model_name='thana',
            constraint=models.UniqueConstraint(fields=('city', 'name'), name='delivery_unique_thana_per_city'),
        ),
    ]
